# ==========================
# BLACK & WHITE KITTY
# ==========================


font_family JetBrainsMono Nerd Font
font_size 14

bold_font auto
italic_font auto
bold_italic_font auto


# Cursor
cursor_shape block
cursor_blink_interval 0


# Window
confirm_os_window_close 0

background_opacity 0.82
background_blur 20


# Padding
window_padding_width 12


# Colors

foreground #ffffff
background #090909

selection_foreground #000000
selection_background #ffffff


# Cursor color

cursor #ffffff


# URL

url_color #aaaaaa
url_style underline


# Tabs minimal

tab_bar_style powerline
tab_bar_background #090909


# Disable annoying effects

enable_audio_bell no
visual_bell_duration 0


# Smooth scrolling

scrollback_lines 10000
