hl.on("hyprland.start", function ()
    hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-hyprland")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("waybar")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("tailscale up")
    hl.exec_cmd("swaybg -m fill -i ~/.config/hypr/wallpapers/eldenring.jpg")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-gammarelay")
end)
