general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 3
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = rgb(ffffff)
    inner_color = rgba(000000, 0.8)
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text = <i>Inserisci password...</i>
}

label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
